// automatically generated by the FlatBuffers compiler, do not modify

package com.leegm.common.protocol;

public final class Event {
  private Event() { }
  public static final byte UP = 0;
  public static final byte DOWN = 1;
  public static final byte LEFT = 2;
  public static final byte RIGHT = 3;
  public static final byte ATTACK = 4;

  public static final String[] names = { "UP", "DOWN", "LEFT", "RIGHT", "ATTACK", };

  public static String name(int e) { return names[e]; }
}

