// automatically generated by the FlatBuffers compiler, do not modify

package com.leegm.common.protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Inventory extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static Inventory getRootAsInventory(ByteBuffer _bb) { return getRootAsInventory(_bb, new Inventory()); }
  public static Inventory getRootAsInventory(ByteBuffer _bb, Inventory obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Inventory __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.leegm.common.protocol.Item items(int j) { return items(new com.leegm.common.protocol.Item(), j); }
  public com.leegm.common.protocol.Item items(com.leegm.common.protocol.Item obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o) + j * 8, bb) : null; }
  public int itemsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public com.leegm.common.protocol.Item.Vector itemsVector() { return itemsVector(new com.leegm.common.protocol.Item.Vector()); }
  public com.leegm.common.protocol.Item.Vector itemsVector(com.leegm.common.protocol.Item.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 8, bb) : null; }

  public static int createInventory(FlatBufferBuilder builder,
      int itemsOffset) {
    builder.startTable(1);
    Inventory.addItems(builder, itemsOffset);
    return Inventory.endInventory(builder);
  }

  public static void startInventory(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addItems(FlatBufferBuilder builder, int itemsOffset) { builder.addOffset(0, itemsOffset, 0); }
  public static void startItemsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 4); }
  public static int endInventory(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Inventory get(int j) { return get(new Inventory(), j); }
    public Inventory get(Inventory obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

