// automatically generated by the FlatBuffers compiler, do not modify

package com.leegm.common.protocol;

public final class Method {
  private Method() { }
  public static final byte NONE = 0;
  public static final byte CREATE = 1;
  public static final byte READ = 2;
  public static final byte UPDATE = 3;
  public static final byte DELETE = 4;

  public static final String[] names = { "NONE", "CREATE", "READ", "UPDATE", "DELETE", };

  public static String name(int e) { return names[e]; }
}

