// automatically generated by the FlatBuffers compiler, do not modify

package com.leegm.common.protocol;

public final class ResultCode {
  private ResultCode() { }
  public static final byte SUCCESS = 0;
  public static final byte ERROR = 1;

  public static final String[] names = { "SUCCESS", "ERROR", };

  public static String name(int e) { return names[e]; }
}

