// automatically generated by the FlatBuffers compiler, do not modify

package com.leegm.common.protocol;

public final class State {
  private State() { }
  public static final byte IDLE = 0;
  public static final byte MOVE = 1;
  public static final byte ATTACK = 2;
  public static final byte DEAD = 3;

  public static final String[] names = { "IDLE", "MOVE", "ATTACK", "DEAD", };

  public static String name(int e) { return names[e]; }
}

