// automatically generated by the FlatBuffers compiler, do not modify

package com.leegm.common.protocol;

public final class TypeCode {
  private TypeCode() { }
  public static final byte PLAYER = 0;
  public static final byte NPC = 1;
  public static final byte OBJECT = 2;

  public static final String[] names = { "PLAYER", "NPC", "OBJECT", };

  public static String name(int e) { return names[e]; }
}

